config/routes.rb
Mebay::Application.routes.draw do

  delete 'ads/:id/delete', to: 'ads#destroy'
  patch 'ads/:id/update', to: 'ads#update'
  get 'ads/:id/edit', to: 'ads#edit'
  get '/ads/new', to: 'ads#new'
  post 'ads/create', to: 'ads#create'
  get '/ads/', to: 'ads#index'
  get '/ads/:id', to: 'ads#show'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  before_filter :authenticate, only: [:edit, :update, :destroy]

  def index
    @ads = Ad.find(:all)
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.save
    redirect_to "/ads/#{@ad.id}"
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    @ad.update(params_ad)
    redirect_to ads_url
  end

  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to "/ads"
  end


  private
    def params_ad
      params.require(:ad).permit(:name, :description, :price, :seller_id, :email, :img_url)
    end

    def authenticate
        authenticate_or_request_with_http_basic('Ads') do |username, password|
          username == 'admin' && password == 'password'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/create.html.erb
<h1>Anuncio criado</h1>
<p>Visualize seu anuncio <a href="<%=@ad.id%>">aqui</a></p>

app/views/ads/edit.html.erb
<h1>Editar anúncio</h1>

<%= form_for @ad, :url => {:controller => "ads", :action => "update"} do |f| %>
  <p><b>Nome</b></br><%= f.text_field :name%></p>
  <p><b>Descrição</b></br><%= f.text_area :description%></p>
  <p><b>Preço</b></br><%= f.text_field :price%></p>
  <p><b>ID Vendedor</b></br><%= f.text_field :seller_id%></p>
  <p><b>Email</b></br><%= f.text_field :email%></p>
  <p><b>Img URL</b></br><%= f.text_field :img_url%></p>
  <p><%= f.submit "Salvar" %></p>
<% end %>

app/views/ads/index.html.erb
 <h1>Todos os anúncios</h1>
  <ul>
    <% for ad in @ads %>
      <li><a href="/ads/<%= ad.id %>"><%= ad.name %></a>
      [<a href="/ads/<%= ad.id %>/delete">Excluir</a>]</li>
    <% end %>
  </ul>

app/views/ads/new.html.erb
<h1>Novo anúncio</h1>

<%= form_for @ad, url: ads_create_path do |f| %>
  <p><b>Nome</b></br><%= f.text_field :name%></p>
  <p><b>Descrição</b></br><%= f.text_area :description%></p>
  <p><b>Preço</b></br><%= f.text_field :price%></p>
  <p><b>ID Vendedor</b></br><%= f.text_field :seller_id%></p>
  <p><b>Email</b></br><%= f.text_field :email%></p>
  <p><b>Img URL</b></br><%= f.text_field :img_url%></p>
  <p><%= f.submit "Criar" %></p>
<% end %>

app/views/ads/show.html.erb
<p>
  <b>Name: </b><%=  @ad.name %>
</p>
<p>
  <b>Descrição: </b><%=  @ad.description %>
</p>
<p>
  <b>Preço: </b><%=  @ad.price %>
</p>
<p>
  <b>ID Vendedor: </b><%=  @ad.seller_id %>
</p>
<p>
  <b>Email: </b><%=  @ad.email %>
</p>
<p>
  <img src="<%=  @ad.img_url %>"/>
</p>
<p>
  <%= link_to "Editar", "#{@ad.id}/edit" %>
</p>
<p>
  <%= link_to "Excluir", "#{@ad.id}/delete" %>
</p>

app/views/ads/update.html.erb
<h1>Anuncio atualizado</h1>
<p>Visualize seu anuncio <a href="<%=@ad.id%>">aqui</a></p>

app/views/layouts/ads.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Ads: <%= controller.action_name %></title>
</head>
<body>
    <div id="wrapper">
    <div id="header">
      <div>

        <h1>MeBay</h1>
        <ul id="nav">
          <li><a href="/ads/">All Ads</a></li>
        </ul>
      </div>
    </div>

    <div id="content">
      <%= yield %>
    </div>
    <div id="clearfooter"></div>
    </div>
  <div id="footer"></div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mebay</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>